### ISSUE TITLE
Same table is being multiple times

### ISSUE THREAD

**Issue by sirius-sama** [itsmikepowers/apollo-easy-scrape#3]
Hi, Mike!

This script adds the same table multiple times. Could you please look at this issue?

I also want to ask if you have abandoned this script. Please let us know if you did.

Thanks.

**Comment by itsmikepowers** [comment]
Theres not much I can do its just the way apollo presents the data. They show duplicate to prevent this type of thing. Rerun the scrape twice and filter out any duplicates afterward. Hope this helps
